networks:
  network:
    driver: bridge

services:

  sette_mezzo:
    image: sette_mezzo:latest
    container_name: sette_mezzo
    build:
      context: .
    ports:
      - "4000:80"
    networks:
      - network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www.danilocatone.com.cer:/etc/nginx/www.danilocatone.com.cer
      - ./nginx/www.danilocatone.com.key:/etc/nginx/www.danilocatone.com.key